export enum CART_ACTION_TYPES {
  ADD_PRODUCT = "cart/ADD_PRODUCT",
  REMOVE_PRODUCT = "cart/REMOVE_PRODUCT",
  CLEAR_PRODUCT_FROM_CART = "cart/CLEAR_PRODUCT_FROM_CART",
  CLEAR_CART = "cart/CLEAR_CART",
  TOGGLE_CART = "cart/TOGGLE_CART"
}
